### ISSUE TITLE
certificate password

### ISSUE THREAD

**Issue by ZaunSupremoXV** [googleapis/google-p12-pem#269]
HELP
NOTE: the certificate has a password

![Captura de Tela (9)](https://user-images.githubusercontent.com/67069017/86927551-d758aa00-c109-11ea-922b-0b28ac2fe544.png)

**Comment by sofisl** [comment]
Hi @ZaunSupremoXV,

When you first create your p12 key, the console will show a pop up with the password. Your computer should prompt you for the password when you open it locally. Afterwards, you can just use the path to which you saved your key to run the sample, and it should return the pem.

Hope this helps! Feel free to reopen if not.
