### ISSUE TITLE
Vulnerability of dependency node-forge

### ISSUE THREAD

**Issue by kimskimchi** [googleapis/google-p12-pem#295]
We've been notified that a dependency of google-p12-pem, the node-forge package has a vulnerability and that it is fixed in v0.10.0. The current version that is being used by google-p12-pem is of version 0.9.

**Comment by rohansingh** [comment]
Looks like that was actually fixed in v3.0.3 by #292.

**Comment by sofisl** [comment]
Will close for now, feel free to reopen.

**Comment by cmanzi-microdrop** [comment]
Apparently this has not actually been fixed in node-forge@v0.10.0: https://github.com/digitalbazaar/forge/issues/857
