### ISSUE TITLE
GPL2 License issue

### ISSUE THREAD

**Issue by RezaRahmati** [googleapis/google-p12-pem#377]
Hi 

There is a GPL2 licensing issue on `node-forge@0.10.0` which is direct dependency

[here](https://github.com/digitalbazaar/forge/blob/cbebca3780658703d925b61b2caffb1d263a6c1d/LICENSE) is the link to license page

**Comment by bcoe** [comment]
Hey @RezaRahmati, thanks for brining this up.

`node-forge` is dual licensed under BSD-3-Clause OR GPL-2.0, we have elected to use it under the BSD-3-Clause.

Let me know if you have any follow up questions.
