### ISSUE TITLE
Update node-forge dependency

### ISSUE THREAD

**Issue by ramicohen303** [googleapis/google-p12-pem#383]
npm audit generates the following error for node-forge < 1.0.0:
Prototype Pollution in node-forge debug API. - https://github.com/advisories/GHSA-5rrq-pxf6-6jx5

**Comment by xHyroM** [comment]
https://github.com/googleapis/google-p12-pem/pull/382

**Comment by SurferJeffAtGoogle** [comment]
Fixed by https://github.com/googleapis/google-p12-pem/pull/382

**Comment by ramicohen303** [comment]
Thank you for the quick resolution
