### ISSUE TITLE
Build broken due to update of "colors" package

### ISSUE THREAD

**Issue by mnahkies** [googleapis/google-p12-pem#385]
The release #384 containing a security fix (https://github.com/googleapis/google-p12-pem/pull/382) appears to be blocked by CI due to the sabotaged colors package having updated (https://github.com/Marak/colors.js/issues/285)

I notice that this repository doesn't have a `package-lock.json` or `yarn.lock` file in it - should one be added to help avoid this kind of unexpected breakage in future?

**Comment by SurferJeffAtGoogle** [comment]
There are trade offs for checking in the package-lock.json.   Paging @bcoe for an explanation.

**Comment by bcoe** [comment]
the bad release of colors was rolled back on the weekend by npm/GitHub, which unblocked #384. Security patch should be out in the wild.
