### ISSUE TITLE
feature request: move away from utilizing node-forge

### ISSUE THREAD

**Issue by ddelgrosso1** [googleapis/google-p12-pem#419]
Currently this library utilizes node-forge to convert between p12 format and pem format. According to [bundlephobia](https://bundlephobia.com/package/@google-cloud/storage@6.4.1) node-forge currently accounts for ~35% of the size of NodeJS Storage. Considering we are utilizing a very limited amount of node-forge functionality we should investigate the possibility of moving away from it for something lighter weight.

**Comment by ddelgrosso1** [comment]
Created this to better track the comments in https://github.com/googleapis/google-p12-pem/issues/414

**Comment by mehboob-at-ibm** [comment]
Is there an ETA for this to be completed?

**Comment by ddelgrosso1** [comment]
We decided to remove google-p12-pem further up the chain of auth flow (https://github.com/googleapis/node-gtoken/pull/452). As a result it is unlikely we will remove node-forge from this library. Closing as a result.
